"""splicecraft_cassette — eukaryotic transcription-unit assembler (layer L3).

The nuclear-expression counterpart to `splicecraft_biology._assemble_operon`.
That function assembles a BACTERIAL operon (one promoter, many RBS+CDS, one
terminator) and its hard problem is translation initiation — each RBS has to
be reverse-designed against its real upstream context. A plant nuclear
transcription unit has the opposite shape: ONE coding block, but a stack of
positional regulatory parts around it (promoter / 5'UTR / intron / signal
peptide / CDS / C-tag / terminator), and its hard problems are

  * **frame** — the signal peptide, the mature CDS and any C-terminal tag are
    one continuous ORF spread across three separately-sourced parts, so a part
    whose length is not a multiple of 3 frameshifts everything downstream of
    it. Silent in a plasmid map, fatal in planta.
  * **motif hygiene** — the coding block has to lose polyadenylation signals,
    mRNA instability motifs, cryptic splice sites and the assembly enzyme's
    own recognition sites, WITHOUT changing the protein.
  * **assembly-scar compatibility** — Type IIS overhangs have to chain
    promoter→UTR→CDS→tag→terminator and be mutually distinct, or the one-pot
    reaction misassembles.
  * **internal repeats** — a clonally-propagated host (any vegetatively
    multiplied crop) cannot segregate away a silenced insert, so
    a long direct repeat inside one T-DNA is a permanent liability rather than
    an F2 inconvenience.

This module answers those four and nothing else: it is a PURE assembler over
already-retrieved parts. It does not fetch sequence, pick promoters, or decide
biology — callers do that and hand in the parts.

`_assemble_expression_cassette` mirrors `_assemble_operon`'s contract on
purpose: same JSON-serialisable dict return, same "layout TILES the sequence
with no gap or overlap" guarantee, same raise-ValueError-on-bad-input
discipline, so the agent endpoint and the UI can treat the two alike.

**Parts are dicts, not a `Part` class.** Everything crossing the agent-API
boundary in this codebase is JSON, and `_assemble_operon` already sets the
precedent (`genes` is a list of dicts). A part is
``{'name': str, 'seq': str, 'type': str?}``; a bare `str` is accepted and
promoted to a part with a positional default name.

**Scrubbing only ever touches the coding block.** Synonymous codon swaps are
safe by construction; a promoter or terminator has no synonymous
representation, so "fixing" a motif there would silently break the part. A
motif that lands in a non-coding part — or straddles a junction such that no
codon swap can clear it — is REPORTED as a residual, never edited. That
asymmetry is the whole safety story of this module.

**Cryptic splice sites are scored, not regexed.** `GT` and `AG` each occur
every ~16 bp by chance, so pattern-matching them flags the whole CDS. The check
delegates to `splicecraft_splice`, whose clade-matched PWMs rank a candidate
against real plant splice sites and against unused GT/AG dinucleotides. Sites
are REPORTED, not auto-edited: clearing one costs a synonymous swap that may
create a different problem, and a donor/acceptor PAIR at intron spacing is a
far stronger signal than either alone. When no model is loaded the check says
so — it never returns an empty list that would read as "clean".

Layer L3: imports state(L0), biology(L0), logging(L0), splice(L0),
dataaccess(L1), codon(L2). Nothing here imports the hub or any L4+ sibling, so
the module is importable from tests and headless agent runs without booting the
app.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # annotation-only; the real Bio import is lazy, inside the fn
    from Bio.SeqRecord import SeqRecord

import splicecraft_state as _state
from splicecraft_biology import _forbidden_hit_set, _rc
from splicecraft_codon import (   # L2 (downward; codon never imports cassette)
    _codon_fix_gc_window, _codon_fix_sites, _codon_gc, _codon_gc3,
    _codon_gc_window_range,
)
from splicecraft_dataaccess import _BUILTIN_GRAMMARS
from splicecraft_logging import _log
from splicecraft_splice import (   # L0
    _splice_model_summary, _splice_pair_risk, _splice_scan,
)

# ── Element order. This IS the cassette's grammar: the tuple order is the
# 5'→3' order in the emitted sequence, and every layout/frame/overhang report
# is generated by walking it, so adding an element type here is the single
# edit needed to extend the assembler. ──────────────────────────────────────
_CASSETTE_ELEMENTS: tuple[str, ...] = (
    'promoter', 'utr5', 'intron', 'signal_peptide', 'cds', 'ctag', 'terminator',
)

# The contiguous ORF. These three parts are translated as ONE protein, so they
# are the only elements the frame checker constrains and the only ones the
# motif scrubber is allowed to rewrite.
_CODING_ELEMENTS: tuple[str, ...] = ('signal_peptide', 'cds', 'ctag')

# element → INSDC feature key for GenBank emission. Deliberately reuses the
# vocabulary already in `_GB_PART_TYPE_TO_INSDC` (dataaccess) so a cassette
# renders with the same feature types as a domesticated Golden-Braid part.
_CASSETTE_INSDC: dict[str, str] = {
    'promoter':       'promoter',
    'utr5':           "5'UTR",
    'intron':         'intron',
    'signal_peptide': 'sig_peptide',
    'cds':            'CDS',
    'ctag':           'CDS',
    'terminator':     'terminator',
}

# element → MoClo/Golden-Braid grammar position type, for overhang lookup.
# `intron` rides in the 5'UTR position (it is physically inside the leader) and
# `signal_peptide` rides in the CDS position (it is the ORF's 5' end) — both
# are sub-parts of a grammar slot rather than slots of their own.
_CASSETTE_POSITION_TYPE: dict[str, str] = {
    'promoter':       'Promoter',
    'utr5':           "5' UTR",
    'intron':         "5' UTR",
    'signal_peptide': 'CDS',
    'cds':            'CDS',
    'ctag':           'C-tag',
    'terminator':     'Terminator',
}

# Motifs scrubbed out of the coding block by default. Every one is a real,
# published failure mode in plant nuclear expression:
_CASSETTE_MOTIFS: dict[str, str] = {
    # Canonical plant polyadenylation signals — premature 3'-end processing
    # truncates the transcript mid-CDS.
    'polyA_AATAAA':  'AATAAA',
    'polyA_AATAAT':  'AATAAT',
    # AU-rich element; binds destabilising factors and shortens mRNA half-life.
    'ARE_ATTTA':     'ATTTA',
}

# Type IIS recognition sites scrubbed so the cassette survives its own
# assembly reaction (and the next level's). Both strands are handled by
# `_codon_fix_sites`, which adds the reverse complement of any non-palindromic
# site automatically.
_CASSETTE_ENZYME_SITES: dict[str, str] = {
    'BsaI':  'GGTCTC',
    'BsmBI': 'CGTCTC',    # = Esp3I
    'BpiI':  'GAAGAC',    # = BbsI
    'BtgZI': 'GCGATG',
    'AarI':  'CACCTGC',
    'SapI':  'GCTCTTC',
}

# Homopolymer run that trips synthesis and slips polymerases.
_CASSETTE_MAX_HOMOPOLYMER = 6

# GC band enforced over a sliding window across the coding block.
_CASSETTE_GC_WINDOW = 50
_CASSETTE_GC_MIN = 40.0
_CASSETTE_GC_MAX = 70.0

# A repeat this long inside one T-DNA is a recombination / silencing liability.
_CASSETTE_REPEAT_MIN = 100

# Scrub iteration cap. Clearing one motif can create another, so the passes
# loop; this bounds the loop and the residual report says what survived.
_CASSETTE_SCRUB_ROUNDS = 20


def _cassette_part(value, label: str) -> dict:
    """Normalise a caller's part into ``{'name', 'seq', 'type'}``.

    Accepts a dict (canonical), a bare string (promoted, named after its
    slot), or None/empty (absent). Raises ValueError on a non-ACGT sequence
    rather than letting an ambiguity code reach the codon layer, where it
    would surface as a confusing translation error three frames later."""
    if value is None:
        return {}
    if isinstance(value, str):
        value = {'name': label, 'seq': value}
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a dict, a string, or None")
    seq = str(value.get('seq') or value.get('sequence') or '').strip().upper()
    seq = seq.replace('U', 'T')
    if not seq:
        return {}
    bad = set(seq) - set('ACGT')
    if bad:
        raise ValueError(
            f"{label} must be unambiguous A/C/G/T — found {sorted(bad)}")
    return {'name': str(value.get('name') or label), 'seq': seq,
            'type': str(value.get('type') or _CASSETTE_POSITION_TYPE.get(label, ''))}


def _cassette_homopolymer_runs(dna: str, max_run: int) -> "list[dict]":
    """Every run of identical bases LONGER than ``max_run``.

    Reported, not auto-fixed: a run inside the coding block is cleared by the
    scrub's synonymous passes, but one inside a promoter is the caller's
    problem to accept or re-source."""
    hits, n = [], len(dna)
    i = 0
    while i < n:
        j = i
        while j + 1 < n and dna[j + 1] == dna[i]:
            j += 1
        run = j - i + 1
        if run > max_run:
            hits.append({'base': dna[i], 'start': i, 'length': run})
        i = j + 1
    return hits


def _cassette_internal_repeats(dna: str, min_len: int,
                               exclude: "list[tuple[int, int]] | None" = None
                               ) -> "list[dict]":
    """Direct and inverted repeats of ``min_len``+ bases WITHIN one sequence.

    A clonally-propagated host cannot segregate away a silenced insert, so
    an internal repeat is permanent. Both orientations
    matter: a direct repeat recombines out the intervening DNA, an inverted
    repeat folds into the hairpin that seeds RNA-directed DNA methylation.

    ``exclude`` is a list of ``(start, end)`` spans whose PAIRWISE repeats are
    intentional — the flanking MAR pair being the motivating case. A hit is
    dropped only when BOTH of its copies sit inside excluded spans, so a MAR
    that accidentally repeats against the promoter is still reported.

    Reports the maximal repeat per seed rather than every one of the
    ``run - min_len + 1`` overlapping windows a naive k-mer sweep emits."""
    n = len(dna)
    if min_len <= 0 or n < min_len * 2:
        return []
    exclude = exclude or []

    def _excluded(pos: int, length: int) -> bool:
        return any(s <= pos and pos + length <= e for s, e in exclude)

    index: "dict[str, list[int]]" = {}
    for i in range(n - min_len + 1):
        index.setdefault(dna[i:i + min_len], []).append(i)

    hits, seen = [], set()
    for kmer, positions in index.items():
        if len(positions) > 1:
            first, second = positions[0], positions[1]
            if (first, second, 'direct') in seen:
                continue
            # Extend right for the maximal run so one repeat is one finding.
            run = min_len
            while (second + run < n
                   and dna[first + run] == dna[second + run]):
                run += 1
            if _excluded(first, run) and _excluded(second, run):
                continue
            for off in range(run - min_len + 1):
                seen.add((first + off, second + off, 'direct'))
            hits.append({'kind': 'direct', 'length': run,
                         'positions': sorted(positions)[:8],
                         'seq_head': dna[first:first + min(min_len, 40)]})

    rc = _rc(dna)
    for i in range(n - min_len + 1):
        window = rc[i:i + min_len]
        for j in index.get(window, []):
            # Map the RC coordinate back to the forward strand.
            fwd = n - i - min_len
            if fwd <= j:
                continue
            if (j, fwd, 'inverted') in seen:
                continue
            if _excluded(j, min_len) and _excluded(fwd, min_len):
                continue
            seen.add((j, fwd, 'inverted'))
            hits.append({'kind': 'inverted', 'length': min_len,
                         'positions': [j, fwd], 'seq_head': window})

    hits.sort(key=lambda h: (-h['length'], h['positions'][0]))
    return hits


def _cassette_frame_report(parts: dict) -> "list[dict]":
    """Frame at every translational junction of the signal-peptide → CDS →
    C-tag ORF.

    Frame is cumulative: an element whose length is not a multiple of 3 shifts
    everything 3' of it, so the report walks the coding elements in order and
    carries the running offset. ``offset_in`` is the frame the element starts
    in (0 = correct); an element is `in_frame` only when it BOTH starts at
    offset 0 and is itself codon-aligned, because either failure breaks the
    protein."""
    report, offset = [], 0
    for elem in _CODING_ELEMENTS:
        part = parts.get(elem) or {}
        seq = part.get('seq') or ''
        if not seq:
            continue
        length = len(seq)
        report.append({
            'element':    elem,
            'name':       part.get('name', elem),
            'length':     length,
            'offset_in':  offset,
            'codon_aligned': length % 3 == 0,
            'in_frame':   offset == 0 and length % 3 == 0,
        })
        offset = (offset + length) % 3
    if report:
        report[-1]['offset_out'] = offset
    return report


def _cassette_scrub_targets(enzyme: str, extra: "dict | None",
                            include_default_motifs: bool) -> "dict[str, str]":
    """The ``{name: site}`` dict handed to `_codon_fix_sites`.

    Always includes the assembly enzyme AND the level-up enzyme of any
    built-in grammar that uses it, because a cassette that survives its own
    reaction but dies in the next one is a bug the caller will not see until
    L1 assembly fails."""
    targets: "dict[str, str]" = {}
    if include_default_motifs:
        targets.update(_CASSETTE_MOTIFS)
    name = (enzyme or '').strip()
    for key, site in _CASSETTE_ENZYME_SITES.items():
        if key.lower() == name.lower():
            targets[key] = site
            break
    else:
        if name:
            raise ValueError(
                f"unknown enzyme {enzyme!r} — known: "
                f"{sorted(_CASSETTE_ENZYME_SITES)}")
    for grammar in _BUILTIN_GRAMMARS.values():
        if str(grammar.get('enzyme', '')).lower() == name.lower():
            up = str(grammar.get('level_up_enzyme') or '')
            site = _CASSETTE_ENZYME_SITES.get(up)
            if site:
                targets[up] = site
    if extra:
        for key, site in extra.items():
            site = str(site or '').strip().upper()
            if site and set(site) - set('ACGT'):
                raise ValueError(f"forbidden motif {key!r} must be A/C/G/T")
            if site:
                targets[str(key)] = site
    return targets


def _cassette_scan_motifs(seq: str, targets: "dict[str, str]") -> "list[dict]":
    """Every forbidden-motif occurrence in ``seq``, ON BOTH STRANDS.

    Two traps this exists to avoid, both of which produce a clean-looking
    empty result rather than an error:

    1. `_forbidden_hit_set` takes an ITERABLE OF SITE STRINGS, not a
       ``{name: site}`` dict. Handing it the dict iterates the KEYS, which
       aren't valid IUPAC, so every one is skipped and the scan reports
       nothing. A silent all-clear on a cassette full of BsaI sites.
    2. It scans the given patterns against the forward strand only. A Type IIS
       enzyme is non-palindromic and cuts just as well from the bottom strand,
       so a reverse-complement hit is a real site that a forward-only scan
       calls clean. `_codon_fix_sites` adds the RC internally for its own
       repair, but the audit path has to add it here.

    Returns ``[{motif, site, strand, position}]`` sorted by position, where
    `position` is always a FORWARD-strand coordinate."""
    lookup: "dict[str, list[tuple[str, str]]]" = {}
    for name, site in targets.items():
        site = str(site or '').upper()
        if not site:
            continue
        lookup.setdefault(site, []).append((name, '+'))
        rc = _rc(site)
        if rc != site:
            lookup.setdefault(rc, []).append((name, '-'))
    hits: "list[dict]" = []
    for site, owners in lookup.items():
        for found, pos in _forbidden_hit_set(seq, [site]):
            for name, strand in owners:
                hits.append({'motif': name, 'site': found,
                             'strand': strand, 'position': pos})
    hits.sort(key=lambda h: (h['position'], h['motif'], h['strand']))
    return hits


def _cassette_scrub_coding(dna: str, protein: str, raw: dict,
                           targets: "dict[str, str]", *,
                           rounds: int, transl_table: "int | None",
                           gc_window: int, gc_min: float, gc_max: float,
                           ) -> tuple:
    """Iteratively clear ``targets`` + the GC band from a coding sequence.

    Clearing a restriction site can create a polyadenylation signal and
    vice-versa, so the passes loop until a full round changes nothing
    (converged) or ``rounds`` is spent. Returns
    ``(dna, {'rounds', 'converged', 'fixes', 'residual_motifs',
    'gc_window_range'})``.

    The protein is the invariant: every pass is synonymous, so a residual is
    always "this motif cannot be removed without changing the protein", never
    "this motif was left because we gave up on correctness"."""
    fixes: "list[dict]" = []
    converged, used = False, 0
    for _ in range(max(1, int(rounds))):
        used += 1
        before = dna
        dna, site_fixes = _codon_fix_sites(
            dna, protein, raw, targets, has_appended_stop=True,
            transl_table=transl_table)
        for fix in site_fixes:
            fixes.append({'pass': 'site', **(fix if isinstance(fix, dict)
                                             else {'detail': fix})})
        dna, gc_fixes = _codon_fix_gc_window(
            dna, protein, raw, window=gc_window, min_gc=gc_min, max_gc=gc_max,
            sites=targets, has_appended_stop=True, transl_table=transl_table)
        for fix in gc_fixes:
            fixes.append({'pass': 'gc', **(fix if isinstance(fix, dict)
                                           else {'detail': fix})})
        if dna == before:
            converged = True
            break
    residual = sorted({h['motif'] for h in _cassette_scan_motifs(dna, targets)})
    return dna, {
        'rounds':          used,
        'converged':       converged,
        'fixes':           fixes,
        'residual_motifs': residual,
        'gc_window_range': _codon_gc_window_range(dna, gc_window),
    }


def _cassette_overhangs(grammar_id: str, elements: "list[str]") -> "dict":
    """Type IIS fusion sites for the occupied positions, and the one failure
    mode that actually ruins a one-pot reaction.

    Overhangs in MoClo/Golden-Braid are a property of the POSITION, not of the
    part, and several cassette elements share a position (`utr5` + `intron`
    both ride the 5'UTR slot; `signal_peptide` + `cds` are both the CDS slot).
    Those are one physical fragment, so they contribute one junction, not two.

    A cassette that SKIPS a position is normal and not an error: omitting the
    C-tag means the CDS fragment is simply domesticated to carry the
    terminator's 5' fusion site (`GGTA`) instead of the C-tag's (`GCTT`). So
    each junction reports the `required` overhang — the downstream position's
    oh5, which is what the upstream part must be built to end in — plus
    `nominal`, the grammar's default for that upstream position, and whether
    the two agree. A disagreement is a build instruction, not a defect.

    The real defect is a **duplicate**: two DIFFERENT junctions demanding the
    same 4-nt fusion site. Those ligate in either order, so the reaction yields
    a mixture and the right clone becomes a screening problem. That, and only
    that, is what the caller warns on."""
    grammar = _BUILTIN_GRAMMARS.get(grammar_id) or {}
    positions = {str(p.get('type')): p for p in grammar.get('positions', [])}
    rows, order = [], []
    for elem in elements:
        ptype = _CASSETTE_POSITION_TYPE.get(elem)
        # An unmapped element has no position type at all, which is not the
        # same as "a type that this grammar lacks" — keep it None so the row
        # and the note below report it honestly, and skip the lookup.
        pos = positions.get(ptype) if ptype else None
        row = {'element': elem, 'position_type': ptype,
               'position': (pos or {}).get('name'),
               'oh5': (pos or {}).get('oh5'), 'oh3': (pos or {}).get('oh3')}
        if not pos:
            row['note'] = f"grammar {grammar_id!r} has no {ptype!r} position"
        rows.append(row)
        # Collapse elements sharing one grammar slot into a single fragment.
        if not order or order[-1]['position'] != row['position']:
            order.append({'position': row['position'], 'elements': [elem],
                          'oh5': row['oh5'], 'oh3': row['oh3']})
        else:
            order[-1]['elements'].append(elem)

    chain: "list[dict]" = []
    for left, right in zip(order, order[1:]):
        required = right.get('oh5')
        nominal = left.get('oh3')
        chain.append({
            'from': '+'.join(left['elements']),
            'to': '+'.join(right['elements']),
            'required': required,
            'nominal': nominal,
            'nominal_match': bool(required) and required == nominal,
        })

    # Every fusion site the one-pot reaction has to discriminate: the 5' end of
    # the first fragment, each internal junction, and the 3' end of the last.
    sites: "dict[str, list[str]]" = {}
    if order:
        if order[0].get('oh5'):
            sites.setdefault(order[0]['oh5'], []).append("5' end")
        for junction in chain:
            if junction['required']:
                sites.setdefault(junction['required'], []).append(
                    f"{junction['from']}→{junction['to']}")
        if order[-1].get('oh3'):
            sites.setdefault(order[-1]['oh3'], []).append("3' end")
    duplicates = {oh: users for oh, users in sites.items() if len(users) > 1}
    return {'positions': rows, 'chain': chain, 'fusion_sites': sites,
            'duplicates': duplicates}


def _assemble_expression_cassette(promoter, utr5=None, intron=None,
                                  signal_peptide=None, cds=None, ctag=None,
                                  terminator=None, *,
                                  codon_table: "dict | None" = None,
                                  protein: "str | None" = None,
                                  scrub_motifs: bool = True,
                                  enzyme: str = 'BsaI',
                                  grammar: str = 'moclo_plant',
                                  forbidden_motifs: "dict | None" = None,
                                  transl_table: "int | None" = None,
                                  scrub_rounds: int = _CASSETTE_SCRUB_ROUNDS,
                                  gc_window: int = _CASSETTE_GC_WINDOW,
                                  gc_min: float = _CASSETTE_GC_MIN,
                                  gc_max: float = _CASSETTE_GC_MAX,
                                  repeat_min: int = _CASSETTE_REPEAT_MIN,
                                  repeat_exclude=None,
                                  check_splice: bool = True,
                                  dry_run: bool = False) -> dict:
    """Assemble a plant nuclear transcription unit from positional parts.

    The eukaryotic sibling of `_assemble_operon`. Order is fixed by
    `_CASSETTE_ELEMENTS`::

        promoter - utr5 - intron - signal_peptide - cds - ctag - terminator

    Every argument except `promoter` and `cds` is optional; each is a part
    dict ``{'name', 'seq'}``, a bare DNA string, or None. Returns::

        {sequence, layout, frame, scrub, overhangs, repeats,
         homopolymers, stats, warnings, dry_run}

    `sequence` is DNA. `layout` is the ordered element map
    ``[{kind, name, start, end}]`` where ``sequence[start:end]`` is EXACTLY
    that element — contiguous, no gaps or overlaps, the same tiling contract
    `_assemble_operon` guarantees. `frame` reports the running frame at every
    junction of the signal-peptide→CDS→C-tag ORF. `scrub` reports the
    synonymous-rewrite passes and, crucially, what SURVIVED them.

    **Scrubbing needs the protein.** Synonymous swapping is only meaningful
    against a known translation, so `scrub_motifs=True` requires both
    `codon_table` (a raw ``{codon: (aa, count)}`` usage dict, the shape stored
    in the codon registry and used by `_codon_optimize`) and either `protein`
    or a coding block whose length is a multiple of 3 (translated via the
    `_state` hook). Without them the scrub
    is skipped and a warning is emitted rather than the sequence being
    silently rewritten against a guessed frame.

    `dry_run=True` performs every check and returns the full report with the
    assembled sequence, but marks the result so callers know not to emit
    files. The assembly itself is pure — nothing is written either way — so
    dry-run is a signal to the CALLER's file emitter, not a different code
    path here.

    Raises ValueError on a non-ACGT part, an unknown enzyme, an out-of-frame
    coding block when scrubbing was requested, or an empty cassette."""
    supplied = {
        'promoter': promoter, 'utr5': utr5, 'intron': intron,
        'signal_peptide': signal_peptide, 'cds': cds, 'ctag': ctag,
        'terminator': terminator,
    }
    parts = {k: _cassette_part(v, k) for k, v in supplied.items()}
    present = [e for e in _CASSETTE_ELEMENTS if parts.get(e)]
    if not present:
        raise ValueError("cassette is empty — supply at least a promoter and a CDS")

    # Validate the enzyme up front: it is a plain argument error, and finding
    # out about it only after translating the ORF buries the real complaint
    # under whatever the codon layer says next.
    targets_all = _cassette_scrub_targets(enzyme, forbidden_motifs, True)

    warnings: "list[str]" = []
    for required in ('promoter', 'cds'):
        if not parts.get(required):
            warnings.append(f"no {required} — the cassette will not express")

    # ── Frame, BEFORE any scrub. A frameshifted coding block must not be
    # handed to the codon layer: it would translate in the wrong frame and
    # "preserve" a protein that was never real. ──────────────────────────
    frame = _cassette_frame_report(parts)
    broken = [f for f in frame if not f['in_frame']]
    coding = ''.join((parts.get(e) or {}).get('seq', '') for e in _CODING_ELEMENTS)

    scrub_report: dict = {'skipped': True, 'reason': 'not requested'}
    if scrub_motifs and coding:
        if broken:
            raise ValueError(
                "cannot scrub an out-of-frame coding block: "
                + "; ".join(f"{f['element']} (len {f['length']}, "
                            f"starts at offset {f['offset_in']})"
                            for f in broken))
        if not codon_table:
            scrub_report = {'skipped': True,
                            'reason': 'no codon_table supplied'}
            warnings.append(
                "motif scrub skipped — pass codon_table to enable synonymous "
                "rewriting")
        else:
            aa = protein
            if aa is None:
                # `_translate_cds(full_seq, start, end, strand, ...)` — the
                # coding block is already spliced and forward, so it is the
                # whole span on the plus strand.
                aa = _state._translate_cds_hook(
                    coding, 0, len(coding), 1,
                    transl_table=int(transl_table or 1))
            aa = str(aa or '').rstrip('*')
            if not aa:
                raise ValueError(
                    "coding block did not translate — pass `protein` explicitly")
            if '*' in aa:
                raise ValueError(
                    "coding block contains an internal stop codon; refusing to "
                    "scrub a sequence whose translation is already broken")
            scrubbed, scrub_report = _cassette_scrub_coding(
                coding, aa, codon_table, targets_all, rounds=scrub_rounds,
                transl_table=transl_table, gc_window=gc_window,
                gc_min=gc_min, gc_max=gc_max)
            if len(scrubbed) != len(coding):
                raise ValueError(
                    "scrub changed the coding block length — refusing to "
                    "re-tile a cassette whose frame moved")
            # Re-tile the scrubbed coding block back across its elements; the
            # element lengths are unchanged, so the offsets still hold.
            at = 0
            for elem in _CODING_ELEMENTS:
                part = parts.get(elem)
                if not part:
                    continue
                width = len(part['seq'])
                part['seq'] = scrubbed[at:at + width]
                at += width
            coding = scrubbed
            scrub_report['skipped'] = False
            if not scrub_report['converged']:
                warnings.append(
                    f"motif scrub hit the {scrub_rounds}-round cap without "
                    f"converging; residuals: "
                    f"{scrub_report['residual_motifs'] or 'none'}")
            if scrub_report['residual_motifs']:
                warnings.append(
                    "motifs survived synonymous scrubbing (cannot be removed "
                    "without changing the protein): "
                    + ", ".join(scrub_report['residual_motifs']))

    # ── Tile. Built AFTER scrubbing so layout coordinates describe the
    # sequence actually returned. ────────────────────────────────────────
    sequence, layout = '', []
    for elem in _CASSETTE_ELEMENTS:
        part = parts.get(elem)
        if not part:
            continue
        start = len(sequence)
        sequence += part['seq']
        layout.append({'kind': elem, 'name': part['name'],
                       'start': start, 'end': len(sequence),
                       'insdc': _CASSETTE_INSDC.get(elem, 'misc_feature')})

    # ── Post-assembly checks over the WHOLE cassette, including the junctions
    # that per-part checks structurally cannot see. ──────────────────────
    whole = _cassette_scan_motifs(sequence, targets_all)
    coding_span = None
    if any(parts.get(e) for e in _CODING_ELEMENTS):
        starts = [r['start'] for r in layout if r['kind'] in _CODING_ELEMENTS]
        ends = [r['end'] for r in layout if r['kind'] in _CODING_ELEMENTS]
        coding_span = (min(starts), max(ends))
    junction_hits = []
    for hit in whole:
        pos, site = hit['position'], hit['site']
        inside = (coding_span is not None
                  and coding_span[0] <= pos
                  and pos + len(site) <= coding_span[1])
        junction_hits.append({**hit, 'in_coding': inside,
                              'fixable_synonymously': inside})
    if junction_hits:
        outside = [h for h in junction_hits if not h['in_coding']]
        if outside:
            warnings.append(
                f"{len(outside)} forbidden-motif hit(s) lie outside the coding "
                "block (in a regulatory part or across a junction) and CANNOT "
                "be cleared by synonymous swaps — re-source the part or move "
                "the junction")

    # ── Cryptic splice sites (§1.4.4). Scanned over the assembled cassette on
    # the SENSE strand only: the transcript is single-stranded and only the
    # sense strand is spliced, so a reverse-strand "site" is not a hazard here.
    # Only the TRANSCRIBED region can be spliced. The promoter is upstream of
    # the transcription start and never appears in the mRNA, so scanning it
    # manufactures false alarms — and expensive ones: a "donor" in the promoter
    # pairs with a real acceptor downstream and reports an intron that would
    # excise the whole CDS, which reads as catastrophic and is not real. The
    # transcript starts at the first element after the promoter.
    splice: dict = {'skipped': True, 'reason': 'not requested'}
    if check_splice:
        tx_start = next((r['start'] for r in layout if r['kind'] != 'promoter'), 0)
        tx = sequence[tx_start:]
        try:
            hits = _splice_scan(tx, kind='both')
            pairs = _splice_pair_risk(tx, kind='both')
            for h in hits:                      # back to cassette coordinates
                h['position'] += tx_start
            for p in pairs:
                p['donor']['position'] += tx_start
                p['acceptor']['position'] += tx_start
            splice = {'skipped': False, 'sites': hits, 'pairs': pairs[:20],
                      'transcript_start': tx_start,
                      'model': _splice_model_summary().get('source', '?')}
            in_coding = [h for h in hits
                         if coding_span and coding_span[0] <= h['position']
                         < coding_span[1]]
            if in_coding:
                warnings.append(
                    f"{len(in_coding)} cryptic splice site(s) in the coding "
                    "block score as strongly as real plant splice sites")
            if pairs:
                frame_losing = [p for p in pairs if p['in_frame_loss']]
                warnings.append(
                    f"{len(pairs)} donor/acceptor PAIR(S) at plausible intron "
                    f"spacing — these can excise sequence from the transcript"
                    + (f"; {len(frame_losing)} would delete a whole number of "
                       "codons, so the product could still be ELISA-positive "
                       "while being wrong" if frame_losing else ""))
        except RuntimeError as exc:
            # No trained model: report honestly, never imply 'clean'.
            splice = {'skipped': True, 'reason': str(exc)}
            warnings.append("splice-site check SKIPPED — " + str(exc))

    repeats = _cassette_internal_repeats(sequence, repeat_min,
                                         exclude=repeat_exclude)
    if repeats:
        warnings.append(
            f"{len(repeats)} internal repeat(s) >= {repeat_min} bp — a clonal "
            "host cannot segregate a silenced insert away")

    homopolymers = _cassette_homopolymer_runs(sequence, _CASSETTE_MAX_HOMOPOLYMER)
    overhangs = _cassette_overhangs(grammar, present)
    missing = [r for r in overhangs['positions'] if not r.get('position')]
    if missing:
        warnings.append(
            "no grammar position for: "
            + ", ".join(f"{r['element']} ({r['position_type']})"
                        for r in missing))
    if overhangs['duplicates']:
        warnings.append(
            "duplicate fusion sites will misassemble: "
            + ", ".join(f"{oh} used at {' and '.join(u)}"
                        for oh, u in overhangs['duplicates'].items()))
    adjusted = [c for c in overhangs['chain'] if not c['nominal_match']]
    if adjusted:
        warnings.append(
            "position(s) skipped — domesticate the upstream part to these "
            "fusion sites instead of the grammar default: "
            + ", ".join(f"{c['from']}→{c['to']} needs {c['required']} "
                        f"(default {c['nominal']})" for c in adjusted))

    stats = {
        'length':      len(sequence),
        'gc':          round(_codon_gc(sequence), 2),
        'coding_len':  len(coding),
        'gc3_coding':  round(_codon_gc3(coding), 2) if coding else None,
        'elements':    present,
    }
    _log.info("cassette assembled: %d bp, %d elements, %d warning(s)%s",
              len(sequence), len(present), len(warnings),
              " [dry-run]" if dry_run else "")
    return {
        'sequence':     sequence,
        'layout':       layout,
        'frame':        frame,
        'scrub':        scrub_report,
        'motif_hits':   junction_hits,
        'overhangs':    overhangs,
        'repeats':      repeats,
        'splice':       splice,
        'homopolymers': homopolymers,
        'stats':        stats,
        'warnings':     warnings,
        'dry_run':      bool(dry_run),
    }


def _cassette_to_record(result: dict, name: str, *,
                        description: str = '',
                        notes: "dict | None" = None,
                        topology: str = 'linear') -> "SeqRecord":
    """Render an assembled cassette as an annotated Biopython `SeqRecord`.

    Every layout element becomes a properly TYPED INSDC feature (`promoter`,
    `5'UTR`, `intron`, `sig_peptide`, `CDS`, `terminator`) rather than a pile
    of `misc_feature`s with labels — the distinction is what lets SnapGene and
    SpliceCraft render the map correctly and what makes the file survive a
    round-trip through another tool.

    `notes` maps an element kind to free text stapled onto that feature as a
    `/note` qualifier. This is the channel for construct-level caveats that
    must not get lost in handoff."""
    from Bio.Seq import Seq                       # lazy: keeps import cost off L3
    from Bio.SeqFeature import FeatureLocation, SeqFeature
    from Bio.SeqRecord import SeqRecord

    seq = result['sequence']
    record = SeqRecord(Seq(seq), id=name[:16] or 'CASSETTE', name=name[:16] or 'CASSETTE',
                       description=description or f"expression cassette {name}")
    record.annotations['molecule_type'] = 'DNA'
    record.annotations['topology'] = topology
    record.annotations['source'] = description or name

    notes = notes or {}
    for row in result['layout']:
        qualifiers = {'label': [row['name']]}
        kind = row['kind']
        if kind in ('cds', 'signal_peptide', 'ctag'):
            qualifiers['codon_start'] = ['1']
        note = notes.get(kind)
        if note:
            qualifiers['note'] = [note]
        record.features.append(SeqFeature(
            FeatureLocation(int(row['start']), int(row['end']), strand=1),
            type=row['insdc'], qualifiers=qualifiers))

    # One CDS feature spanning the WHOLE ORF, so a viewer translates the real
    # protein instead of three disjoint fragments.
    coding = [r for r in result['layout'] if r['kind'] in _CODING_ELEMENTS]
    if len(coding) > 1:
        record.features.append(SeqFeature(
            FeatureLocation(int(coding[0]['start']), int(coding[-1]['end']),
                            strand=1),
            type='CDS',
            qualifiers={'label': [f"{name} ORF"], 'codon_start': ['1'],
                        'note': ['full open reading frame: '
                                 + ' + '.join(r['name'] for r in coding)]}))
    return record
